### ISSUE TITLE
You can take Items out of the menu with Hotkeys

### ISSUE THREAD

**Issue by Maxetto** [limbo56/PlayerSettings#10]
Using Hotkeys to swap content of your hotbar with things inside the menu allows to put and take items to and from the Menu.

This means that [InventoryClickEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryClickEvent.html) is not cancelled.

**Comment by limbo56** [comment]
Thanks for reporting, it will be solved for next update!
