### ISSUE TITLE
[FEATURE] Back item

### ISSUE THREAD

**Issue by zArtemis-java** [limbo56/PlayerSettings#23]
Hi @lim_bo56 
Could you add an item that allows you to close the gui or run a command so that it can go back to another menu which I create for example with deluxemenus.
An example:
back_item:
  enabled: true
  name: '&aBack'
  material: ARROW
  amount: 1
  lore: false or (- '')
  slot: 2
  onClick:
  - profilegui

If there are multiple pages, can you make sure that this item is on all pages?

**Comment by limbo56** [comment]
Hello @zArtemis-java. I'm pretty sure you can already create an item that runs a command. You could create an item that runs the command to open the other menu. Besides that, I think a close button will be a good addition as we currently don't have one.

Thank you for your suggestion. Next time make sure you use the [feature request template](https://github.com/limbo56/PlayerSettings/blob/master/.github/ISSUE_TEMPLATE/feature_request.md).
