### ISSUE TITLE
[BUG] ArmorStand 

### ISSUE THREAD

**Issue by zArtemis-java** [limbo56/PlayerSettings#24]
There is also a last bug, when I try to right click on an armature it tells me that I have disabled the stacker. You can remove the stacker with the armature, if I assign a command to an armature that freezes and does not execute the command but gives me the message of the stacker. Also if I disable the stacker instead and try to click on an armorstand it gives me an error in the console

**Comment by limbo56** [comment]
Do you have the stacktrace of the error it throws whenever you click the armor stand? Also, I'll be adding a feature to disable the stacker message in the next update.

Thanks for your report. Next time, make sure to use the [bug report template](https://github.com/limbo56/PlayerSettings/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
