### ISSUE TITLE
[FEATURE] Custom Texture Items,Blocs etc. (CustomModelData)

### ISSUE THREAD

**Issue by Zsomi4** [limbo56/PlayerSettings#36]
**Is your feature request related to a problem? Please describe.**

For me, it's a bit frustrating because my server has a custom texture and unfortunately there is no setting yet that allows me to set custom textured items.

**Describe the solution you'd like**

With this option, you can set custom textured items. Which you can do by setting `CustomModelData: 0` in the items.yml file.

**Describe alternatives you've considered**

N/A

**Specific version**

1.17.x - Newest Versions(1.18.x, 1.19.x, 1.20.x, etc.)

**Comment by limbo56** [comment]
Thanks a lot for your suggestion! Indeed, it's a bit frustrating not having the option to change the custom model data of items. I'll make sure to include this option in the next release.

**Comment by Zsomi** [comment]
😁

**Comment by Zsomi** [comment]
Ohh it would also be a good idea to turn off the br/off indicator item in the menu (Red_dye, lime_dye). Instead a place holder would indicate if the option is on or off.

**Comment by limbo56** [comment]
Hey, I included a new option to disable to toggle button in PR #38. As for the placeholders, there are already some placeholders that you can use on the item's lore [see here](https://github.com/limbo56/PlayerSettings/blob/master/bukkit/src/main/resources/items.yml#L32-L37). Thanks again for your suggestions!
