### ISSUE TITLE
[FEATURE] HEX Color

### ISSUE THREAD

**Issue by Zsomi4** [limbo56/PlayerSettings#37]
**Is your feature request related to a problem? Please describe.**

In the newer versions it is now possible to use rgb and hex colors but unfortunately I can't do it in this plugin yet.

**Describe the solution you'd like**

Enables hex and rgb colors in all config files.

**Describe alternatives you've considered**

N/A

**Specific version**

1.16-Newest Versions

**Comment by limbo56** [comment]
Thank you for your excellent suggestions! Having support for hex colors is a must for new server versions, so I will also be including this in the next release.

**Comment by Zsomi** [comment]
Ohh it would also be a good idea to turn off the br/off indicator item in the menu (Red_dye, lime_dye). Instead a place holder would indicate if the option is on or off.
