### ISSUE TITLE
[BUG] Settings move over to the other worlds

### ISSUE THREAD

**Issue by GodDirtman** [limbo56/PlayerSettings#44]
**Describe the bug**

Settings move over to the other worlds, even if they are not enabled in the config.

**To Reproduce**
1. Have at least 2 worlds in your server (`A` and `B` for example).
2. In the `config.yml`, set in which worlds you want the settings to be available (`A` for example).
3. As a player, enable or disable any setting in the GUI while in the world `A` (speed for example).
4. Change the world to `B`.
5. Your settings are still working in this world (so you can have a boosted speed in the `B` world following the example).

**Expected behavior**

Settings should apply only to the worlds they were set in. 

**Server version**

`This server is running Paper version git-Paper-263 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 3ac1a8d)`

**Additional context**

I'm using Multiverse-Core 4.3.1 for multiple worlds.

**Comment by limbo56** [comment]
Hello 👋

Thanks a lot for reporting this bug. I noticed this also happens when you disable settings through the configuration and reload the plugin. I will look into this further and include a fix in the next update.
