### ISSUE TITLE
[BUG] 1.21 is not supported

### ISSUE THREAD

**Issue by frafol** [limbo56/PlayerSettings#63]
**Describe the bug**
The plugin is not starting in 1.21, even with default configurations.

**To Reproduce**

1. Install spigot/paper 1.21.
2. Start the server.
3. See error.

**Expected behavior**
The plugin should start without errors.

**Server version**
This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

**Additional context**
Console error: https://pastebin.com/TWguwtqR
Plugin's items.yml: https://pastebin.com/xwDTVWxv

**Comment by limbo56** [comment]
Thank you for reporting this issue! It should be resolved in the latest version. Please reopen the issue if the problem persists.
