### ISSUE TITLE
MySQL settings doesn't get saved

### ISSUE THREAD

**Issue by Maxetto** [limbo56/PlayerSettings#9]
With MySQL Player Settings don't get saved and loaded correctly.

They are all deactivated.

**Comment by Maxetto** [comment]
Will look into it tomorrow

**Comment by Maxetto** [comment]
I reloaded the plugin and it seems to work now... Very strange 😛 

I'll close this, will update if there are any news.

**Comment by limbo56** [comment]
The problem is that the settings are only saved when the player leaves the server, and I don't now any existing way to save it when before the plugin is disabled, It can be done by caching data, but it will be too much saved data.

**Comment by Maxetto** [comment]
So, i've managed out how to reproduce it.

Basically it only happens when the player data is loaded for the 1st time from Database.
This means when you restart.

This also means that config's defaults don't get loaded and all defaults to false to new players... This is something that shouldn't happen!

**Comment by limbo56** [comment]
Weird, I'll have a look at the code, it should be solved for the next update. Thanks for reporting the issue!
